export const endpoints = Object.freeze({
  health: "/health",
  ready: "/ready",
  auth: {
    register: "/api/v1/auth/register",
    login: "/api/v1/auth/login",
    refresh: "/api/v1/auth/refresh",
    logout: "/api/v1/auth/logout",
    me: "/api/v1/auth/me",
  },
  adminRoleRequests: {
    create: "/api/v1/admin-role-requests",
    mine: "/api/v1/admin-role-requests/me",
    cancel: (requestId) => `/api/v1/admin-role-requests/${requestId}`,
  },
  admin: {
    auth: {
      login: "/api/v1/admin/auth/login",
      refresh: "/api/v1/admin/auth/refresh",
      logout: "/api/v1/admin/auth/logout",
      logoutAll: "/api/v1/admin/auth/logout-all",
      me: "/api/v1/admin/auth/me",
    },
    dashboard: "/api/v1/admin/dashboard",
    users: {
      list: "/api/v1/admin/users",
      detail: (userId) => `/api/v1/admin/users/${userId}`,
      update: (userId) => `/api/v1/admin/users/${userId}`,
      suspend: (userId) => `/api/v1/admin/users/${userId}/suspend`,
      reactivate: (userId) => `/api/v1/admin/users/${userId}/reactivate`,
      remove: (userId) => `/api/v1/admin/users/${userId}`,
      revokeSessions: (userId) => `/api/v1/admin/users/${userId}/revoke-sessions`,
      promote: (userId) => `/api/v1/admin/users/${userId}/promote`,
    },
    administrators: {
      list: "/api/v1/admin/administrators",
      detail: (adminId) => `/api/v1/admin/administrators/${adminId}`,
      demote: (adminId) => `/api/v1/admin/administrators/${adminId}/demote`,
      suspend: (adminId) => `/api/v1/admin/administrators/${adminId}/suspend`,
      reactivate: (adminId) => `/api/v1/admin/administrators/${adminId}/reactivate`,
      revokeSessions: (adminId) =>
        `/api/v1/admin/administrators/${adminId}/revoke-sessions`,
    },
    adminRequests: {
      create: "/api/v1/admin/admin-role-requests",
      list: "/api/v1/admin/admin-role-requests",
      mine: "/api/v1/admin/admin-role-requests/mine",
      detail: (requestId) => `/api/v1/admin/admin-role-requests/${requestId}`,
      approve: (requestId) => `/api/v1/admin/admin-role-requests/${requestId}/approve`,
      reject: (requestId) => `/api/v1/admin/admin-role-requests/${requestId}/reject`,
      requestInformation: (requestId) =>
        `/api/v1/admin/admin-role-requests/${requestId}/request-information`,
    },
    incidents: {
      list: "/api/v1/admin/incidents",
      detail: (incidentId) => `/api/v1/admin/incidents/${incidentId}`,
      approve: (incidentId) => `/api/v1/admin/incidents/${incidentId}/approve`,
      reject: (incidentId) => `/api/v1/admin/incidents/${incidentId}/reject`,
      update: (incidentId) => `/api/v1/admin/incidents/${incidentId}`,
      merge: (incidentId) => `/api/v1/admin/incidents/${incidentId}/merge`,
      reviewLock: (incidentId) => `/api/v1/admin/incidents/${incidentId}/review-lock`,
    },
    posts: {
      list: "/api/v1/admin/posts",
      detail: (postId) => `/api/v1/admin/posts/${postId}`,
      update: (postId) => `/api/v1/admin/posts/${postId}`,
      hide: (postId) => `/api/v1/admin/posts/${postId}/hide`,
      restore: (postId) => `/api/v1/admin/posts/${postId}/restore`,
      remove: (postId) => `/api/v1/admin/posts/${postId}`,
    },
    comments: {
      list: "/api/v1/admin/comments",
      detail: (commentId) => `/api/v1/admin/comments/${commentId}`,
      update: (commentId) => `/api/v1/admin/comments/${commentId}`,
      hide: (commentId) => `/api/v1/admin/comments/${commentId}/hide`,
      restore: (commentId) => `/api/v1/admin/comments/${commentId}/restore`,
      remove: (commentId) => `/api/v1/admin/comments/${commentId}`,
    },
    audit: "/api/v1/admin/audit",
    settings: "/api/v1/admin/settings",
    agent: {
      status: "/api/v1/admin/agent",
      start: "/api/v1/admin/agent/runs",
      cancel: (runId) => `/api/v1/admin/agent/runs/${runId}/cancel`,
    },
    events: "/api/v1/admin/events/stream",
  },
  geolocation: {
    cities: "/api/v1/geolocation/cities",
    config: "/api/v1/geolocation/config",
    cell: "/api/v1/geolocation/cell",
    heatmap: "/api/v1/geolocation/heatmap",
    hexagon: (h3Index) => `/api/v1/geolocation/hexagons/${h3Index}`,
    hexagonStatistics: (h3Index) =>
      `/api/v1/geolocation/hexagons/${h3Index}/statistics`,
  },
  incidents: {
    list: "/api/v1/incidents",
    nearby: "/api/v1/incidents/nearby",
    types: "/api/v1/incidents/types",
    reports: "/api/v1/incidents/reports",
    detail: (incidentId) => `/api/v1/incidents/${incidentId}`,
  },
  statistics: {
    overview: "/api/v1/statistics/overview",
    timeseries: "/api/v1/statistics/timeseries",
    hourly: "/api/v1/statistics/hourly",
    types: "/api/v1/statistics/types",
  },
});
